apiVersion: v1
entries:
  biend-wordpress-basic:
  - apiVersion: v2
    appVersion: "6.4"
    created: "2026-02-24T20:26:15.2080217-03:00"
    description: WordPress b√°sico com Nginx, PHP 8.3, MySQL/MariaDB e Redis em pods
      separados
    digest: a240207ff041398bbc567990ff8a782abed35c11d96ae6f52ab687949dade2eb
    home: https://github.com/fexdelux
    keywords:
    - wordpress
    - nginx
    - php
    - mysql
    - mariadb
    - redis
    maintainers:
    - email: support@techarch.com
      name: TechArch
    name: biend-wordpress-basic
    sources:
    - https://github.com/fexdelux/biend-wordpress-basic
    type: application
    urls:
    - https://fexdelux.github.io/charts/biend-wordpress-basic-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-24T20:26:15.2068868-03:00"
