{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "biend-wordpress-basic.fullname" . }}-mysql-secret
  labels:
    {{- include "biend-wordpress-basic.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}