{{- if and .Values.redis.enabled .Values.redis.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "biend-wordpress-basic.fullname" . }}-redis-secret
  labels:
    {{- include "biend-wordpress-basic.redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}