{{- if .Values.wordpress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "biend-wordpress-basic.fullname" . }}-wordpress
  labels:
    {{- include "biend-wordpress-basic.wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.wordpress.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "biend-wordpress-basic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
{{- end }}