{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "biend-wordpress-basic.fullname" . }}-mysql
  labels:
    {{- include "biend-wordpress-basic.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "biend-wordpress-basic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}