apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: evolutionapi
commonLabels:
  env: production
  type: api
images:
  - name: image-container-kustomization
    newName: atendai/evolution-api
    newTag: "latest"
resources:
  - configmap.yaml
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml