apiVersion: v2
name: biend-wordpress-basic
description: WordPress b√°sico com Nginx, PHP 8.3, MySQL/MariaDB e Redis em pods separados
type: application
version: 1.0.3
appVersion: "6.4"
keywords:
  - wordpress
  - nginx
  - php
  - mysql
  - mariadb
  - redis
home: https://github.com/fexdelux
sources:
  - https://github.com/fexdelux/biend-wordpress-basic
maintainers:
  - name: BiendIT
    email: support@biend.com.br
